# Generated by Django 2.1.7 on 2023-12-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            # model_name='contact',
            # name='name',
            # field=models.CharField(max_length=50, primary_key=True, serialize=False),
            model_name='contact',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
